In [ ]:
# 第4章 numpy
##http://www.sohu.com/a/206007674_100066998
jupyter notebook使用

In [1]:
#ndarray是一个同构数据多维容器，所有元素必须是相同类型的。每个数组都有一个shape和dtype,list无shape及dtype属性,创建数组最简单的方法是array
import numpy as np
data = np.array([[1,2,3],[4,5,6]])
data.shape


(2, 3)

In [63]:
data.dtype

dtype('int32')

In [64]:
#ndim是维度的意思
data.ndim

2

In [ ]:
np.zeros((3,6))

In [66]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [68]:
#empty返回的是一些未初始化的垃圾值，并不是0，arange返回的是一个ndarray而不是列表，eye创建一个正方形NXN的矩阵对角线为1其余为0，astype方法显式转换其dtype.
data.astype(np.float64)
#不同大小的数组之间的运算叫做广播，另外切片等动作都是作用在视图要想得到一份副本而非视图，就是用copy()函数，使用负数索引是从末尾开始

array([[1., 2., 3.],
       [4., 5., 6.]])

In [71]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [72]:
arr[[1,5,7,2],[0,3,1,2]]


array([ 4, 23, 29, 10])

In [74]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [76]:
#另外一个方法是使用np.ix_函数,花式索引是将新数据复制到新数组中
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# #数组转置及轴对换

In [4]:
#转置返回的是源数据的视图，T属性
import numpy as np
arr = np.arange(15).reshape((3,5))
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [6]:
#np.dot计算的是矩阵的内积,np.dot(x,y)等于x.dot(y),det行列式inv矩阵逆，trace是对角线元素和，diag以一维数组形式返回对角线元素
arr = np.random.randn(6,3)
np.dot(arr.T,arr)

array([[ 2.10889951, -2.30374265, -2.09948561],
       [-2.30374265,  5.46905131,  4.47908169],
       [-2.09948561,  4.47908169, 11.11167571]])

In [8]:
arr.T.dot(arr)

array([[ 2.10889951, -2.30374265, -2.09948561],
       [-2.30374265,  5.46905131,  4.47908169],
       [-2.09948561,  4.47908169, 11.11167571]])

In [9]:
#对于高维数组就需要transpose得到一个由轴编号组成的元组才能对这些轴进行转置
#https://www.cnblogs.com/sunshinewang/p/6893503.html，同理swapaxes也是
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [10]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
#np.maximum(x,y)元素最大值，abs绝对值，sqrt平方根，square平方exp\log\sign,ceil大于等于该值的最小整数floor小于等于该值的最大整数
#np.where(cond,x,y)如果cond为真则x,否则为y. arr.mean()平均值，sum求和，std标准差，cumsum累计和，cumprod累计积
#all()函数用来检查数组中所有值是否都是True

# #排序

In [17]:
#arr.sort()排序，也可以对一个轴向上排序，只需将轴编号传给它,sort返回的是排序好的副本
import numpy as np
arr = np.random.randn(5,3)
arr 

array([[ 0.69705194,  0.01278663, -0.85752174],
       [ 0.70264387,  1.71368485,  0.24794042],
       [ 1.80786292,  0.44191517,  1.15103621],
       [-0.1908523 ,  0.33649263,  0.73825921],
       [-0.24794173, -1.64675094, -0.37784922]])

In [19]:
arr.sort(1)
arr

array([[-0.85752174,  0.01278663,  0.69705194],
       [ 0.24794042,  0.70264387,  1.71368485],
       [ 0.44191517,  1.15103621,  1.80786292],
       [-0.1908523 ,  0.33649263,  0.73825921],
       [-1.64675094, -0.37784922, -0.24794173]])

In [21]:
#np.unique用于找出数组中唯一值并返回排序好的
ints = np.array([3,3,3,3,2,2,1,1,55])
np.unique(ints)

array([ 1,  2,  3, 55])

In [22]:
#np.in1d测试一个数组中的值在另一个数组中的成员资格，返回布尔型数组
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [ ]:
#np.union1d(x,y)是计算并集并返回有序结果

# #随机数生成

In [23]:
#得到一个标准正态分布的4X4的数组
np.random.normal(size=(4,4))

array([[ 0.76532448, -0.7363776 ,  1.36589159,  1.13546056],
       [-0.30036571, -0.95197556,  2.18705506, -1.05604319],
       [-0.72965865,  1.15299374, -0.04145119, -0.84132079],
       [-2.1359421 ,  0.1563609 ,  2.21430973, -0.38340195]])

# 第5章 pandas入门

## Series

In [2]:
import pandas as pd
import numpy as np
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [28]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [29]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [31]:
obj2 = pd.Series([4,7,-5,3],index=['d','b','c','a'])
obj2

d    4
b    7
c   -5
a    3
dtype: int64

In [32]:
obj2.index

Index(['d', 'b', 'c', 'a'], dtype='object')

In [33]:
obj2['d']

4

In [35]:
sdata = {'c':35000,'a':71000,'d':16000,'b':5000}
pd.Series(sdata)

c    35000
a    71000
d    16000
b     5000
dtype: int64

In [39]:
states = {'ca','a','or','te'}
obj3=pd.Series(sdata,index=states)
obj3
#pandas的isnull和notnull函数可用于检测缺失数据

a     71000.0
or        NaN
te        NaN
ca        NaN
dtype: float64

In [42]:
obj3.name = 'population'
obj3.index.name = 'state'
obj3

state
a     71000.0
or        NaN
te        NaN
ca        NaN
Name: population, dtype: float64

# DataFrame

In [44]:
data = {'state': ['ohio','ohio','ohio','nevada','nevada'],'year': [2000,2001,2002,2001,2002],'pop': [1.5,1.7,3.6,2.4,2.9]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9

In [45]:
#如果指定了序列，则按照指定顺序
frame = pd.DataFrame(data,columns=['year','state','pop'])
frame

year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002    ohio  3.6
3  2001  nevada  2.4
4  2002  nevada  2.9

In [47]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])
frame2

year   state  pop debt
one    2000    ohio  1.5  NaN
two    2001    ohio  1.7  NaN
three  2002    ohio  3.6  NaN
four   2001  nevada  2.4  NaN
five   2002  nevada  2.9  NaN

In [48]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [50]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [51]:
frame2.ix['three']

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2002
state    ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [53]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    ohio  1.5  16.5
two    2001    ohio  1.7  16.5
three  2002    ohio  3.6  16.5
four   2001  nevada  2.4  16.5
five   2002  nevada  2.9  16.5

In [56]:
#另一种数据形式是嵌套字典，传给DataFrame时外层字典键作为列，内层键作为行
pop = {'Necada':{2001:2.4,2002:2.9},'ohio':{2000:1.5,2001:1.7,2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

Necada  ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [57]:
frame3.T

2000  2001  2002
Necada   NaN   2.4   2.9
ohio     1.5   1.7   3.6

In [59]:
frame3.index.name = "year"
frame3.columns.name = 'state'
frame3

state  Necada  ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [60]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [63]:
#Index对象是不可修改的，因此用户不能对其进行修改
obj = pd.Series(range(3),index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [64]:
index[1] = 'd'

TypeError: Index does not support mutable operations

# 基本功能


In [66]:
#reindex 创建一个适用新索引的新对象
obj = pd.Series([4.5,7.2,-5.3,3.6],index = ['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [68]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [69]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [70]:
#method选项可达到插值处理，ffill可实现前向值填充,bfill后项填充
obj3 = pd.Series(['blue','purple','yellow'],index = [0,2,4])
obj3.reindex(range(6),method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
#reindex参数，index method fill_value limit level  copy

In [72]:
#丢掉指定轴上的项
#drop方法返回的是一个指定轴上删除了指定值得新对象
obj = pd.Series(np.arange(5),['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [74]:
new_obj = obj.drop(['c','d'])
new_obj

a    0
b    1
e    4
dtype: int32

In [75]:
#默认情况下，DataFrame和Series之间的算术运算会将Series的索引匹配到DataFrame列，然后沿着行一直向下广播
frame = pd.DataFrame(np.arange(12).reshape(4,3),columns = ['a','b','c'],index=['ut','oh','te','or'])
series = frame.ix[0]
frame

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until


a   b   c
ut  0   1   2
oh  3   4   5
te  6   7   8
or  9  10  11

In [76]:
series

a    0
b    1
c    2
Name: ut, dtype: int32

In [77]:
frame-series

a  b  c
ut  0  0  0
oh  3  3  3
te  6  6  6
or  9  9  9

In [ ]:
#apply()方法将函数应用到由各列或行所形成的一维数组上


In [78]:
#sort_index实现对行或列的索引进行排序，sort_index(ascending=False)降序
#按值对Series进行排序可使用order方法，排序时任何缺失值可放到Seriesd的末尾
#DataFrame中，对一个或多大列中的值进行排序可利用by选项
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,-1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2 -1

In [79]:
frame.sort_index(by='b')

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  """Entry point for launching an IPython kernel.


b  a
2 -3  0
3  2 -1
0  4  0
1  7  1

In [81]:
frame.sort_index(by=['a'])

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  """Entry point for launching an IPython kernel.


b  a
3  2 -1
0  4  0
2 -3  0
1  7  1

In [ ]:
#cov计算协方差,corr计算相关系数
#unique是得到唯一值，value_counts计算隔值出现的频率

# #层次化索引

In [83]:
data = pd.Series(np.random.randn(10),index=[['a','a','a','b','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,2,3]])
data

a  1   -0.779911
   2   -1.575048
   3   -0.752377
b  1    0.887604
   2   -1.539993
   3   -0.842696
c  1   -0.319015
   2   -1.132176
d  2    0.626721
   3   -1.330448
dtype: float64

In [84]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [85]:
data[:,2]

a   -1.575048
b   -1.539993
c   -1.132176
d    0.626721
dtype: float64

In [86]:
#unstack方法可以重新安排到一个DataFrame中,其逆运算就是stack重新安排到Series中
data.unstack()

1         2         3
a -0.779911 -1.575048 -0.752377
b  0.887604 -1.539993 -0.842696
c -0.319015 -1.132176       NaN
d       NaN  0.626721 -1.330448

In [87]:
#对于DataFrame每条轴都可以有分层索引：
frame = pd.DataFrame(np.arange(12).reshape((4,3)),index=[['a','a','b','b'],[1,2,1,2]],columns=[['ohio','ohio','colorado'],['green','red','green']])
frame

ohio     colorado
    green red    green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [88]:
frame.index.names=['key1','key2']
frame.columns.names = ['state','color']
frame

state      ohio     colorado
color     green red    green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [89]:
frame.swaplevel('key1','key2')

state      ohio     colorado
color     green red    green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [92]:
frame.sortlevel(1)

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  """Entry point for launching an IPython kernel.


state      ohio     colorado
color     green red    green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [93]:
frame.sum(level='key2')

state  ohio     colorado
color green red    green
key2                    
1         6   8       10
2        12  14       16

In [94]:
frame.sum(level='color',axis=1)

color      green  red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [97]:
#使用DataFrame的列
frame = pd.DataFrame({'a':range(7),'b':range(7,0,-1),'c':['one','one','one','two','two','two','two'],'d':[0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [102]:
#将列转换为行索引并创建一个新的DataFrame:set_index
frame2 = frame.set_index(['c','d'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [103]:
frame.set_index(['c','d'],drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [104]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [105]:
#整数索引pandas对象的整数索引和列表等有所不一样
ser = pd.Series(np.arange(3))
ser

0    0
1    1
2    2
dtype: int32

In [108]:
ser[-1]

KeyError: -1

In [109]:
#对于非整数索引就没有这样的问题
ser2 = pd.Series(np.arange(3),index=['a','b','c'])
ser2

a    0
b    1
c    2
dtype: int32

In [110]:
ser2[-1]

2

In [111]:
#ix的切片与列表啥的不一样，ix报告最后一位
ser.ix[:1]

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


0    0
1    1
dtype: int32

# 第6章 数据加载、存储与文件格式

In [117]:
#read_csv默认是以逗号分隔
df = pd.read_csv('examples/ex1.csv')
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [122]:
#read_table默认不分隔
pd.read_table('examples/ex1.csv', sep=',')


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [129]:
pd.read_csv('examples/ex2.csv')

1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [132]:
#不要标题行
pd.read_csv('examples/ex2.csv',header = None)

0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [5]:
#指定标题
pd.read_csv('examples/ex2.csv',names=['a','b','c','d','message'])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [6]:
#将其中一列作为DataFrame索引可以使用index_col参数
names = ['a','b','c','d','message']
pd.read_csv('examples/ex2.csv',names=names,index_col='message')

a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [10]:
#多个列作为一个层次化索引，只需传入由列编号或列名组成的列表
pd.read_csv("examples/csv_mindex.csv",index_col=['key1','key2'])

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [12]:
#有些表格不使用固定分隔符，颗编写正则表达式read_table作为分隔符
list(open('examples/ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [15]:
#由于列名比数据行数量少，所以第一行自动为DataFrame索引
result = pd.read_table('examples/ex3.txt',sep='\s+')
result

A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [16]:
#skiprows跳过指定行
pd.read_csv('examples/ex4.csv',skiprows=[0,2,3])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [18]:
#指定为NA
sentinels = {'message':['foo','NA'],'something':['two']}
pd.read_csv('examples/ex5.csv',na_values=sentinels)

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

#
##逐块读取文本文件

In [24]:
result = pd.read_csv('examples/ex6.csv')
result


one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
5     1.817480  0.742273  0.419395 -2.251035   Q
6    -0.776764  0.935518 -0.332872 -1.875641   U
7    -0.913135  1.530624 -0.572657  0.477252   K
8     0.358480 -0.497572 -0.367016  0.507702   S
9    -1.740877 -1.160417 -1.637830  2.172201   G
10    0.240564 -0.328249  1.252155  1.072796   8
11    0.764018  1.165476 -0.639544  1.495258   R
12    0.571035 -0.310537  0.582437 -0.298765   1
13    2.317658  0.430710 -1.334216  0.199679   P
14    1.547771 -1.119753 -2.277634  0.329586   J
15   -1.310608  0.401719 -1.000987  1.156708   E
16   -0.088496  0.634712  0.153324  0.415335   B
17   -0.018663 -0.247487 -1.446522  0.750938   A
18   -0.070127 -1.579097  0.120892  0.671432   F
19   -0.194678 -0.492039  2.359605  0.319810   H
20   -0.248618  0.868707 -0.492226 -0.717959   W
21   -1.091549 -0.867110 -0.647760 -0.832562   C
22    0.641404 -0.138822 -0.621963 -0.284839   C
23    1.216408  0.992687  0.165162 -0.069619   V
24   -0.564474  0.792832  0.747053  0.571675   I
25    1.759879 -0.515666 -0.230481  1.362317   S
26    0.126266  0.309281  0.382820 -0.239199   L
27    1.334360 -0.100152 -0.840731 -0.643967   6
28   -0.737620  0.278087 -0.053235 -0.950972   J
29   -1.148486 -0.986292 -0.144963  0.124362   Y
...        ...       ...       ...       ...  ..
9970  0.633495 -0.186524  0.927627  0.143164   4
9971  0.308636 -0.112857  0.762842 -1.072977   1
9972 -1.627051 -0.978151  0.154745 -1.229037   Z
9973  0.314847  0.097989  0.199608  0.955193   P
9974  1.666907  0.992005  0.496128 -0.686391   S
9975  0.010603  0.708540 -1.258711  0.226541   K
9976  0.118693 -0.714455 -0.501342 -0.254764   K
9977  0.302616 -2.011527 -0.628085  0.768827   H
9978 -0.098572  1.769086 -0.215027 -0.053076   A
9979 -0.019058  1.964994  0.738538 -0.883776   F
9980 -0.595349  0.001781 -1.423355 -1.458477   M
9981  1.392170 -1.396560 -1.425306 -0.847535   H
9982 -0.896029 -0.152287  1.924483  0.365184   6
9983 -2.274642 -0.901874  1.500352  0.996541   N
9984 -0.301898  1.019906  1.102160  2.624526   I
9985 -2.548389 -0.585374  1.496201 -0.718815   D
9986 -0.064588  0.759292 -1.568415 -0.420933   E
9987 -0.143365 -1.111760 -1.815581  0.435274   2
9988 -0.070412 -1.055921  0.338017 -0.440763   X
9989  0.649148  0.994273 -1.384227  0.485120   Q
9990 -0.370769  0.404356 -1.051628 -1.050899   8
9991 -0.409980  0.155627 -0.818990  1.277350   W
9992  0.301214 -1.111203  0.668258  0.671922   A
9993  1.821117  0.416445  0.173874  0.505118   X
9994  0.068804  1.322759  0.802346  0.223618   H
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [25]:
pd.read_csv('examples/ex6.csv',nrows=5)

one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [ ]:
#chunksize参数逐块读取，返回TextParser

In [28]:
#to_csv可以将数据写到一个以逗号分隔的文件中



# 手工处理分隔符格式

In [29]:
pd.read_csv('examples/ex7.csv')

a  b  c
0  1  2  3
1  1  2  3

In [53]:
#对于任何单字符分隔符文件可以直接使用python内置的csv模块。将任意已打开的文件
#的对象传给csv.reader:
import csv 
f = open('examples/ex7.csv')
reader = csv.reader(f)
#对这个reader进行迭代，每行会产生一个元组或列表，并一出了所有引号
for line in reader:
    print(line)
lines = list(csv.reader(open('examples/ex7.csv')))
header,values = lines[0],lines[1:]
#zip() 函数用于将可迭代的对象作为参数，将对象中对应的元素打包成一个个元组，然后返回由这些元组组成的列表。
data_dict = {h:v for h,v in zip(header,zip(*values))}
data_dict

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']


{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [ ]:
#定义csv.Dialect的一个子类即可定义出一个新格式
class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = '""'
reader = csv.reader(f,diaect=my_dialect)

In [ ]:
## 还有一些json、html、url、数据库等方法后续用到就学

# 第7章：数据规整化:清理、转换、合并、重塑

In [61]:
#数据集的合并,这是多对一合并，df1中多个a和b行，df2key每个值对应一行,默认merge做的是“inner”连接”，结果中为交集，其他方式还有left\right\outer
#.外链接求取的是键的并集,left以左为主，right以右为主.这个on参数若没有指定且其他键也未指示则以左右的交集为主
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})
df2 = pd.DataFrame({'key':['a','b','d'],'data2':range(3)})
print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2


In [60]:
pd.merge(df1,df2,on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [71]:
#当列名不同的时候
df3 = pd.DataFrame({'lkey':['b','b','a','c','a','a','b'],'data1':range(7)})
df4 = pd.DataFrame({'rkey':['a','b','d'],'data2':range(3)})
pd.merge(df3,df4,left_on='lkey',right_on='rkey',how='outer')


lkey  data1 rkey  data2
0    b    0.0    b    1.0
1    b    1.0    b    1.0
2    b    6.0    b    1.0
3    a    2.0    a    0.0
4    a    4.0    a    0.0
5    a    5.0    a    0.0
6    c    3.0  NaN    NaN
7  NaN    NaN    d    2.0

In [63]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [68]:
#多对多合并,产生的是行的笛卡尔积，3个b和2个为6个 b
df3 = pd.DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})
df4 = pd.DataFrame({'key':['a','b','a','b','d'],'data2':range(5)})
pd.merge(df3,df4,on='key',how='left')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [70]:
#多个键合并
left = pd.DataFrame({'key1':['foo','foo','bar'],'key2':['one','two','one'],'lval':[1,2,3]})
right = pd.DataFrame({'key1':['foo','foo','bar','bar'],'key2':['one','one','one','two'],'rval':[4,5,6,7]})
pd.merge(left,right,on=['key1','key2'],how='outer')


key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [72]:
pd.merge(left,right,on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [75]:

#suffixes默认为（‘_x,_y’）,sort默认为True
pd.merge(left,right,on='key1',suffixes=('_left','_right'),sort=False)

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

# 索引上的合并

In [78]:
left1 = pd.DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})
right1 = pd.DataFrame({'group_val':[3.5,7]},index=['a','b'])
print(left1)
print(right1)

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5
   group_val
a        3.5
b        7.0


In [84]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

# 轴向连接

In [85]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [87]:
np.concatenate([arr,arr],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
#pandas的concat
s1 = pd.Series([0,1],index=['a','b'])
s2 = pd.Series([2,3,4],index=['c','d','e'])
s3 = pd.Series([5,6],index=['f','g'])
print(s1)
print(s2)
print(s3)

a    0
b    1
dtype: int64
c    2
d    3
e    4
dtype: int64
f    5
g    6
dtype: int64


In [89]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [90]:
pd.concat([s1,s2,s3],axis=1)

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [92]:
s4 = pd.concat([s1*5,s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [93]:
pd.concat([s1,s4],axis=1)

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [95]:
#加上join=‘inner’求交集
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  5

In [97]:
#可以通过join_axes指定要在其他轴上使用的索引
pd.concat([s1,s4],axis=1,join_axes=[['a','c','b','e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [98]:
#在连接轴上创建一个层次化索引，使用keys参数
result = pd.concat([s1,s2,s3],keys=['one','two','three'])

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64

In [100]:
#如果沿着axis=对Series进行合并，则keys就会成为DataFrame的列头：
pd.concat([s1,s2,s3],axis=1,keys=['one','two','three'])

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [ ]:
#如果传入的不是列表而是字典，则字典的键成为keys的值
pd.concat({'level1':df1,'lebel2':df2},axis=1)

In [ ]:
#ignore_index哪些行是无意义的，不保留连接轴上的索引

# 重塑层次化索引

In [102]:
#stack：将数据的列转换为行，unstack将行转换为列，默认操作的是最内层
data = pd.DataFrame(np.arange(6).reshape((2,3)),index = pd.Index(['Ohio','Colorado'],name='state'),columns=pd.Index(['one','two','three'],
                                                                                                                    name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [103]:
data.stack()#将列转换为行，得到Series

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [104]:
data.unstack()#将行变为列

number  state   
one     Ohio        0
        Colorado    3
two     Ohio        1
        Colorado    4
three   Ohio        2
        Colorado    5
dtype: int32

In [106]:
#传入层级编号或名称
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [109]:
data.stack().unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [111]:
data.stack().unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

# 长格式旋转为宽格式

In [ ]:
#不同的item值变为一列，date列中的时间值则做索引，由pivot（）函数实现

# 移除重复数据

In [113]:
data = pd.DataFrame({'k1':['one']*3+['two']*4,'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [115]:
data.duplicated()#默认判断全部列,

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [116]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [118]:
data.drop_duplicates(['k1'])#默认保留第一个出现的值组合，参数task_last=True保留最后一个

k1  k2
0  one   1
3  two   3

# 利用函数或映射进行数据转换

In [120]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],'ounces':[4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [128]:
#编写一映射,Series的map函数
meat_to_animal ={
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon' 
}
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [130]:
data['food'].map(lambda x : meat_to_animal[x.lower()])
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

# 替换值

In [133]:
data = pd.Series([1,-999,2,-999,-1000,3])
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [135]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [136]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [137]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

# 重命名轴索引

In [4]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),index=['Ohio','Colorado','New York'],columns=['one','two','three','four'])

In [5]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [10]:
data.index.map(str.upper)



Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

In [9]:
data.index = data.index.map(str.upper)
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [11]:
#创建数据集转换版（而不是修改原始数据）比较实用的方法是rename
data.rename(index=str.title,columns=str.upper)


ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [14]:
#结合字典型对象实现对部分轴标签的更新
data.rename(index={'Ohio':'INDIANA'},columns={'three':'haa'})

one  two  haa  four
OHIO        0    1    2     3
COLORADO    4    5    6     7
NEW YORK    8    9   10    11

# 离散化和面元划分

In [18]:
#将ages划分为18-25；26-35；35-60；60-100,
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)
cats


[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [19]:
cats.labels


d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [22]:

pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [23]:
#区间将右闭区间修改为开实用right=False进行修改
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [25]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']
pd.cut(ages,bins,labels=group_names)


[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [28]:
data = np.random.rand(20)
pd.cut(data,4,precision=2)

[(0.25, 0.49], (0.00012, 0.25], (0.49, 0.74], (0.74, 0.99], (0.49, 0.74], ..., (0.00012, 0.25], (0.49, 0.74], (0.74, 0.99], (0.49, 0.74], (0.49, 0.74]]
Length: 20
Categories (4, interval[float64]): [(0.00012, 0.25] < (0.25, 0.49] < (0.49, 0.74] < (0.74, 0.99]]

In [31]:
#qcut根据样本分位数进行划分，得到大小基本相等的面元
data = np.random.randn(1000)#正太分布
cats = pd.qcut(data,4)
pd.value_counts(cats)

(0.691, 2.747]      250
(0.0157, 0.691]     250
(-0.648, 0.0157]    250
(-4.079, -0.648]    250
dtype: int64

In [36]:
#numpy.random.permutation函数实现对Series或DataFrame的列的随机排列
df = pd.DataFrame(np.arange(20).reshape((5,4)))
sampler =np.random.permutation(5)
sampler


array([3, 1, 0, 4, 2])

In [37]:
df.take(sampler)


0   1   2   3
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19
2   8   9  10  11

# 计算指标、哑变量

In [40]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})
pd.get_dummies(df['key'])


a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [41]:
#将列加上前缀
dummies = pd.get_dummies(df['key'],prefix='key')
df_withs_dummy = df[['data1']].join(dummies)
df_withs_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [ ]:
#...........

# 字符串操作

In [43]:
val = 'a,b, guido'
val.split(',')


['a', 'b', ' guido']

In [45]:
#strip用于修改空白符换行符
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

# 正则表达式

In [49]:
#加号可以将字符串连接起来，
'a' + ':' + 'b' + ':' +  'guido'


'a:b:guido'

In [50]:
#改进
':'.join(pieces)


'a:b:guido'

In [51]:
#find和index的区别是如果找不到字符串index会引发异常而find返回-1
val.index(',')



1

In [52]:
val.find(':')


-1

In [53]:
val.index(':')

ValueError: substring not found

# 第8章 视图和可视化

# 第9章 数据聚合与分组运算

# groupby

In [58]:
df = pd.DataFrame({'key1':['a','a','b','b','a'],'key2':['one','two','one','two','one'],
                    'data1':np.random.randn(5),'data2':np.random.randn(5)})
df

data1     data2 key1 key2
0  0.061220  0.744235    a  one
1 -0.123130 -1.558018    a  two
2 -1.758252  0.232488    b  one
3  0.863011 -0.125303    b  two
4  0.787880  0.540536    a  one

In [59]:
grouped = df['data1'].groupby(df['key1'])
grouped

In [60]:
grouped.mean()

key1
a    0.24199
b   -0.44762
Name: data1, dtype: float64

In [61]:
#如果我们一次传入多大数组，就会得到不同结果：
means = df['data1'].groupby([df['key1'],df['key2']]).mean()
means

key1  key2
a     one     0.424550
      two    -0.123130
b     one    -1.758252
      two     0.863011
Name: data1, dtype: float64

In [62]:
means.unstack()#内层行转列

key2       one       two
key1                    
a     0.424550 -0.123130
b    -1.758252  0.863011

In [63]:
#分组键可以是任何长度适当数组：
states = np.array(['Ohio','California','California','Ohio','Ohio'])
years = np.array([2005,2005,2006,2005,2006])
df['data1'].groupby([states,years]).mean()

California  2005   -0.123130
            2006   -1.758252
Ohio        2005    0.462116
            2006    0.787880
Name: data1, dtype: float64

In [64]:
#将列名用作分组键：
df.groupby('key1').mean()

data1     data2
key1                   
a     0.24199 -0.091083
b    -0.44762  0.053593

In [65]:
df.groupby(['key1','key2']).mean()

data1     data2
key1 key2                    
a    one   0.424550  0.642385
     two  -0.123130 -1.558018
b    one  -1.758252  0.232488
     two   0.863011 -0.125303

In [ ]:
默认情况下所有数值列都会被聚合

In [66]:
#groupby的size()函数返回一个含有分组大小的Series
df.groupby(['key1','key2']).size()

key1  key2
a     one     2
      two     1
b     one     1
      two     1
dtype: int64

In [67]:
#groupby对象支持迭代
for name,group in df.groupby('key1'):
    print(name)
    print(group)
    

a
     data1     data2 key1 key2
0  0.06122  0.744235    a  one
1 -0.12313 -1.558018    a  two
4  0.78788  0.540536    a  one
b
      data1     data2 key1 key2
2 -1.758252  0.232488    b  one
3  0.863011 -0.125303    b  two


In [69]:
#多重键的情况，元租的第一个元素将会是由键值组成的元组：
for (k1,k2),group in df.groupby(['key1','key2']):
    print(k1,k2)
    print (group)

a one
     data1     data2 key1 key2
0  0.06122  0.744235    a  one
4  0.78788  0.540536    a  one
a two
     data1     data2 key1 key2
1 -0.12313 -1.558018    a  two
b one
      data1     data2 key1 key2
2 -1.758252  0.232488    b  one
b two
      data1     data2 key1 key2
3  0.863011 -0.125303    b  two


In [70]:
pieces = dict(list(df.groupby('key1')))
pieces['b']

data1     data2 key1 key2
2 -1.758252  0.232488    b  one
3  0.863011 -0.125303    b  two

In [71]:
#groupby默认是axis=0上进行的
df.dtypes

data1    float64
data2    float64
key1      object
key2      object
dtype: object

In [74]:
grouped = df.groupby(df.dtypes,axis=1)
dict(list(grouped))

{dtype('float64'):       data1     data2
 0  0.061220  0.744235
 1 -0.123130 -1.558018
 2 -1.758252  0.232488
 3  0.863011 -0.125303
 4  0.787880  0.540536, dtype('O'):   key1 key2
 0    a  one
 1    a  two
 2    b  one
 3    b  two
 4    a  one}

In [ ]:
#如果用一个（单个字符串）或一组（字符串数组）列名对其进行索引，就能实现部分列进行聚合的目的
df.groupby('key1')['data1']=df['data1']groupby(df['key1'])
df.groupby('key1')[['data2']]=df[['data2']].groupby(df['key1'])

In [75]:
#这种索引操作所返回的对象是一个已分组的DataFrame(如果传入的是列表或数组)
#或以分组的Series(如果传入的是标量形式的单个列名)：
df.groupby(['key1','key2'])[['data2']].mean()

data2
key1 key2          
a    one   0.642385
     two  -1.558018
b    one   0.232488
     two  -0.125303

In [76]:
df.groupby(['key1','key2'])['data2'].mean()

key1  key2
a     one     0.642385
      two    -1.558018
b     one     0.232488
      two    -0.125303
Name: data2, dtype: float64

# 通过字典或Series进行分组

In [78]:
people = pd.DataFrame(np.random.randn(5,5),columns=['a','b','c','d','e'],
                      index=['Joe','Steve','Wes','Jim','Travis'])
people.ix[2:3,['b','c']] = np.nan
people

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until


a         b         c         d         e
Joe     2.556242  0.126450  0.351170 -0.387373 -1.049021
Steve  -1.199068 -0.235571 -0.314250  1.375076 -1.676161
Wes    -1.581524       NaN       NaN  0.737278  0.301197
Jim     1.559151 -0.901522  1.182076  1.490264  0.090988
Travis -0.467199  1.776656  1.611682 -0.202953 -0.413875

In [80]:
mapping = {'a':'red','b':'red','c':'blue','d':'blue','e':'red','f':'orange'}
by_column = people.groupby(mapping,axis=1).sum()
by_column

blue       red
Joe    -0.036203  1.633671
Steve   1.060826 -3.110799
Wes     0.737278 -1.280327
Jim     2.672340  0.748617
Travis  1.408729  0.895582

In [81]:
#用Series作为分组键，则pandas会检查Series以确保其索引跟分组轴是对齐的：
map_series = pd.Series(mapping)
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: object

In [82]:
people.groupby(map_series,axis=1).count()

blue  red
Joe        2    3
Steve      2    3
Wes        1    2
Jim        2    3
Travis     2    3

In [84]:
#任何被当做分组键的函数都会在各个索引值上被调用一次，其返回值就会被用作名称
people.groupby(len).sum()

a         b         c         d         e
3  2.533869 -0.775072  1.533246  1.840169 -0.656835
5 -1.199068 -0.235571 -0.314250  1.375076 -1.676161
6 -0.467199  1.776656  1.611682 -0.202953 -0.413875

In [85]:
#将函数跟数组、列表、字典、Series混合使用也不是问题，
key_list = ['one','one','one','two','two']
people.groupby((len,key_list)).min()

a         b         c         d         e
3 one -1.581524  0.126450  0.351170 -0.387373 -1.049021
  two  1.559151 -0.901522  1.182076  1.490264  0.090988
5 one -1.199068 -0.235571 -0.314250  1.375076 -1.676161
6 two -0.467199  1.776656  1.611682 -0.202953 -0.413875

# 数据聚合

In [87]:
df

data1     data2 key1 key2
0  0.061220  0.744235    a  one
1 -0.123130 -1.558018    a  two
2 -1.758252  0.232488    b  one
3  0.863011 -0.125303    b  two
4  0.787880  0.540536    a  one

In [92]:
#如果使用自己的聚合函数，只需将其传入agg方法或aggregate方法：
def peak_to_peak(arr):
    return int(arr.max() - arr.min())
grouped.agg(peak_to_peak)

TypeError: ("unsupported operand type(s) for -: 'str' and 'str'", 'occurred at index 0')

# 面向列的多函数应用

In [ ]:
#如果传入一组函数或函数名，得到的DataFrame的列就会以相应的函数命名，
grouped.agg(['mean','std',peak_to_peak])
#如果传入的是一个由（name,function）元组组成的列表，则个元祖的第一个元素就会被用作DataFrame的列名
ftuples = [('Durchschnitt','mean'),('Abweichung',np.var)]
grouped['tip_pct','total_bill'].agg(ftuples)
#对不同的列应用不同的函数，传入一个字典
grouped.agg({'tip':np.max})

# 分组级运算和转换
# 透视表和交叉表
# 示例

# 第10章 时间序列

In [4]:
from datetime import datetime
now = datetime.now()
now

datetime.datetime(2018, 11, 26, 22, 38, 13, 125610)

In [7]:
now.year
now.month
now.day

26

In [9]:
delta = datetime(2011,1,7) - datetime(2008,6,24,8,15)
delta


datetime.timedelta(926, 56700)

In [10]:
delta.days

926

In [11]:
delta.seconds

56700

In [14]:
from datetime import timedelta
start = datetime(2011,1,7)
start + timedelta(12)

datetime.datetime(2011, 1, 19, 0, 0)

In [ ]:
#datetime模块中的数据类型
date
time
datetime
timedelta

In [15]:
#利用str或strtime方法（传入一个格式化字符串）
stamp =datetime(2011,1,3)
str(stamp)

'2011-01-03 00:00:00'

In [16]:
stamp.strftime('%Y-%m-%d')

'2011-01-03'

In [18]:
#strptime是通过已经格式进行日期解析的最佳方式
value = '2011-01-03'
datetime.strptime(value,'%Y-%m-%d')

datetime.datetime(2011, 1, 3, 0, 0)

In [19]:
from dateutil.parser import parse
parse('2011-01-03')

datetime.datetime(2011, 1, 3, 0, 0)

In [20]:
parse('6/12/2011',dayfirst=True)

datetime.datetime(2011, 12, 6, 0, 0)

# to_datetime()

In [26]:
import pandas as pd
import numpy as np
datestrs = ['7/6/2011','8/6/2011']
pd.to_datetime(datestrs)

DatetimeIndex(['2011-07-06', '2011-08-06'], dtype='datetime64[ns]', freq=None)

# 带有重复索引的时间序列

In [29]:
dates = pd.DatetimeIndex(['1/1/2000','1/2/2000','1/2/2000','1/3/2000'])
dup_ts = pd.Series(np.arange(4),index=dates)
dup_ts

2000-01-01    0
2000-01-02    1
2000-01-02    2
2000-01-03    3
dtype: int32

In [30]:
dup_ts.index.is_unique

False

In [32]:
grouped = dup_ts.groupby(level=0)
grouped.mean()

2000-01-01    0.0
2000-01-02    1.5
2000-01-03    3.0
dtype: float64

In [33]:
grouped.count()

2000-01-01    1
2000-01-02    2
2000-01-03    1
dtype: int64